# Numpy Arrays (Part 3)

###### Shape of an Array
The shape of an array is the number of elements in each dimension.

###### Review
ndim is python Numpy method that find or return the dimension of the given Array.

In [8]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print("ndarray dimensions")
print(a.ndim) #ndim attribute ie. number of dimensions
print(b.ndim)
print(c.ndim)
print(d.ndim)

print("ndarray shape")
print(a.shape) #shape attribute ie. the number of elements in each dimension
print(b.shape)
print(c.shape)
print(d.shape)

ndarray dimensions
0
1
2
3
ndarray shape
()
(5,)
(2, 3)
(2, 2, 3)


###### Numpy Array shape attribute
How do we get the Shape of an Array
- NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements

In [1]:
#import the numpy package
import numpy as np

In [6]:
#Find the shape of the numpy array
n_arr_1 = np.array([10,20,30]) # create a 1D Numpy ndarray object by using array() function
n_arr_2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) # create a 2D NumPy ndarray object by using array() function.
print(n_arr_1.shape)
print(n_arr_2.shape)

(3,)
(2, 4)


The second example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

######  Numpy Array ndmin

Below we will create an array with 7 dimensions using ndmin using a vector with values 1,2,3,4,5,6,7,8,9 and verify that last dimension has value 9

In [7]:
arr_3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9], ndmin=7)

print(arr_3)
print('shape of array :', arr_3.shape)

[[[[[[[1 2 3 4 5 6 7 8 9]]]]]]]
shape of array : (1, 1, 1, 1, 1, 1, 9)


###### Reshaping arrays
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

###### Reshape from 1-D to 2-D

- Convert the following 1-D array with 12 elements into a 2-D array.
- The outermost dimension will have 4 arrays, each with 4 elements:

In [18]:
arr_rs = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]) #create a 1D ndarray object using array() function
newarr = arr_rs.reshape(4, 4) # reshape the 1D array
print(newarr)
print(newarr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)


###### Reshape from 1-D to 3D
- Convert the following 1-D array with 12 elements into a 3-D array.
- The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

In [20]:
arr_rs_2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) #create a 1D ndarray object using array() function
newarr_2 = arr_rs_2.reshape(2,3,2) # reshape the 1D array
print(newarr_2)
print(newarr_2.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
