# Numpy Arrays (Part 2 Basics)

###### Numpy Package Python
NumPy is a Python library used for working with arrays, in which Numpy stands for (numerical python).

In Python we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy. Arrays are very frequently used in data science, where speed and resources are very important.

###### Objectives
- Numpy Array Indexing 

Array indexing (accesing array elements) is the same as accessing an array element. You can access an array element by referring to its index number. The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

- Numpy Array Slicing

Slicing in python means taking elements from one given index to another given index. We pass slice instead of index like this: [start:end]. We can also define the step, like this: [start:end:step]. If we don't pass start its considered 0. If we don't pass end its considered length of array in that dimension. If we don't pass step its considered 1

- Data Types in Numpy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.
- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [2]:
import numpy as np #importing the numpy package

### Numpy Array Indexing

Note

Please see also negative indexing used below !

In [7]:
new_array = np.array([1, 2, 3, 5, 234]) #create a 1d Numoy Array
print(new_array[0]) #print the first element in the numpy array
print(new_array[3]) #print the fourth element in the numpy array
print(new_array[-1]) #negative array indexing (acceses the last element in the array)

1
5
234


In [8]:
print(new_array[0] + new_array[-1]) #Get first and fourth elements from the array and add both elements together

235


Access 2-D Arrays

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the row represents the dimension and the index represents the column.

In [13]:
sec_array = np.array([[2,3,4],[10,12,14]]) #create a 2D Numpy array
print(sec_array[0, 1]) #print second elememt of first row (remember zero indexing)
print(sec_array[1,1]) #print second elememt of second row (remember zero indexing)

3
12


Access 3-D Arrays

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [26]:
third_array = np.array([[[2,3,4],[9,11,13],[22,34,45]]]) #create a 3D Numpy array
print(third_array[0,1,2]) #print third element of the second array of the first array:
print(third_array[0,1,0]) #print second element of the second array of the first array:
print(third_array[0,2,0]) #print third element of the second array of the first array:

13
9
22


### NumPy Array Slicing

REMEMBER

We pass slice instead of index like this: [start:end]. We can also define the step, like this: [start:end:step]. If we don't pass start its considered 0. If we don't pass end its considered length of array in that dimension. If we don't pass step its considered 1.

In [28]:
arr_s = np.array([1, 12, 33, 44, 55, 66, 77]) # create a NumPy ndarray object by using the array() function.
print(arr_s[:4])
print(arr_s[1:3])
print(arr_s[2:6])

[ 1 12 33 44]
[12 33]
[33 44 55 66]


STEP

step value can be used at the end of the slice (determine step) see below !

In [30]:
print(arr_s[2:6:2]) # step value to determine the step of the slicing
print(arr_s[0:6:2]) # step value to determine the step of the slicing
print(arr_s[0:6:3]) # step value to determine the step of the slicing

[33 55]
[ 1 33 55]
[ 1 44]


Slicing 2D Arrays

In [36]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]) # 2D arrays
print(arr[0, 1:4])
print(arr[1, 1:4])
print(arr[0:2, 2]) # from both arrays, return index 2
print(arr[0:2, 1:4]) # From both arrays, slice index 1 to index 4 (not included), this will return a 2-D arraym

[2 3 4]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


###### Data Types in Numpy

Checking the Data Type of an Array

The NumPy array object has a property called dtype that returns the data type of the array:

In [39]:
arr_d = np.array([2,4,6,8,10,12,14,16,18,20,22,24,26,28,30])
arr_s = np.array(['Einsten','Biden','Obama','Musk'])
print(arr_d)
print(arr_d.dtype) # check the data type of the numpy array
print(arr_s)
print(arr_s.dtype) # check the data type of the numpy array

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
int32
['Einsten' 'Biden' 'Obama' 'Musk']
<U7


Creating an array with a defined data type

In [41]:
arr = np.array([1, 2, 3, 4], dtype='f') # create an array with data type float predefined
print(arr)
print(arr.dtype)


[1. 2. 3. 4.]
float32


In [42]:
arr = np.array([1, 2, 3, 4], dtype='i4') # create an array with data type 4 bytes integer
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


###### Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [46]:
# Convert hte numpy array data type from float64 to integer
arr = np.array([1.1, 2.1, 3.1])
print(arr.dtype)
new_arr = arr.astype('i') # astype() function creates a copy of the array and allows you to specify the data type as a parameter.
print(new_arr)
print(new_arr.dtype)

float64
[1 2 3]
int32


In [49]:
# Convert data type from integer to boolean
arr = np.array([1, 0, 3, 5, 0, 7, 0])
new_arr_a = arr.astype(bool)

print(new_arr_a)
print(new_arr_a.dtype)

[ True False  True  True False  True False]
bool
