 # Lists, Dictionaries, np.Arrays Loops and other !

### Lists (while Loops) 

In [2]:
#Initialize offset
offset = -7
#Code a While Loop
while offset != 0:
    print("Correcting...")
    if offset > 0:
        offset = offset - 1
    else:
        offset = offset + 1
    print(offset)

Correcting...
-6
Correcting...
-5
Correcting...
-4
Correcting...
-3
Correcting...
-2
Correcting...
-1
Correcting...
0


### For Loops

for var in seq:
    
    expression

Using a for loop to iterate over a list only gives you access to every list element in each run, one after the other. 
If you also want to access the index information, so where the list element you're iterating over is located, you can use enumerate().

In [8]:
#Initialize a list
fam = ['1.54','1.34','1.76','1.65','1.62','1.75']
#Code a for loop
for x in fam:
    print(x)

1.54
1.34
1.76
1.65
1.62
1.75


x in this case is an arbitraty name in the case of a for loop ie. we can call replace x with any name we would like.

In [17]:
#For Loop (Indexing List)
for index, x in enumerate(fam):
    print("index " + str(index + 1) + " : " + str(x))

index 1 : 1.54
index 2 : 1.34
index 3 : 1.76
index 4 : 1.65
index 5 : 1.62
index 6 : 1.75


In [15]:
#Loop over a string
for x in "family":
    print(x.capitalize())

F
A
M
I
L
Y


In [18]:
# Write a for loop that goes through each sublist of house and prints out the x is y sqm, where x is 
#the name of the room and y is the area of the room.

# Create house list of lists
house = [["hallway", 11.25], 
         ["kitchen", 18.0], 
         ["living room", 20.0], 
         ["bedroom", 10.75], 
         ["bathroom", 9.50]]
         
# Build a for loop from scratch
for x in house :
    print("the " + x[0] + " is " + str(x[1]) + " sqm")

the hallway is 11.25 sqm
the kitchen is 18.0 sqm
the living room is 20.0 sqm
the bedroom is 10.75 sqm
the bathroom is 9.5 sqm


### Dictionaries (Loops)

Dictionaries - If you want iterate over the key, value pairs in a dictionary use the items() method. Order matters in this case in which the first variable gets the key and the second gets the value.

In [28]:
#Creata a Dictionary
Dictionary = {'W':'White','B':'Black','Y':'Yellow','G':'Green','R':'Red','O':'Orange','P':'Purple'}

Note: items() will generate a key and value in each iteration

Also Dictionaries are inherently unorderd and when something is printed returned this will show.

In [24]:
for key, value in Dictionary.items() :
    print(key + " : " + str(value))

W : White
B : Black
Y : Yellow
G : Green
R : Red
O : Orange
P : Purple


In [26]:
for k, v in Dictionary.items():
    print(k + " -- " + str(v))

W -- White
B -- Black
Y -- Yellow
G -- Green
R -- Red
O -- Orange
P -- Purple


### Numpy arrays

Loop over Numpy array
If you're dealing with a 1D Numpy array, looping over all elements can be as simple as:

for x in my_array :
    ...
    
If you're dealing with a 2D Numpy array, it's more complicated. A 2D array is built up of multiple 1D arrays. To explicitly iterate over all separate elements of a multi-dimensional array, you'll need this syntax:

for x in np.nditer(my_array) :
    ...

In [42]:
#Create Two Lists
Weight = [50,60,65,70,75,80,85,90,95,100]
Height = [1.45,1.73,1.65,1.35,1.78,1.43,1.38,1.87,1.91,1.65]
#Create a dictionary
Height_Error = {'95':'cm','100':'cm','125':'cm','135':'cm','155':'cm'}

In [43]:
#import numpy package
import numpy as np

In [46]:
#Convert to Numpy Arrays
Weight_np = np.array(Weight)
Height_np = np.array(Height)
#Print new arrays
print(Weight_a)
print(Height_a)

[ 50  60  65  70  75  80  85  90  95 100]
[1.45 1.73 1.65 1.35 1.78 1.43 1.38 1.87 1.91 1.65]


In [47]:
#Checking types
print(type(Height_np))
print(type(Weight_np))
print(type(Height))
print(type(Weight))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'list'>
<class 'list'>


In [52]:
#Calculate BMI
BMI = Weight_np / Height_np ** 2
#Round BMI
BMI = BMI.round()
print(BMI)
print(type(BMI))

[24. 20. 24. 38. 24. 39. 45. 26. 26. 37.]
<class 'numpy.ndarray'>


In [63]:
#Code a for loop
for val in BMI:
    print(val)

24.0
20.0
24.0
38.0
24.0
39.0
45.0
26.0
26.0
37.0


In [62]:
#Code a for Loop on the 1D array
for val in np.nditer(BMI):
    print(val)

24.0
20.0
24.0
38.0
24.0
39.0
45.0
26.0
26.0
37.0


Using the np.nditer() was for experimental reasons. This executes the same as a 2D array printing all elements in the array. However it is not required for the 1D array.

### 2D Numpy Arrays

If you want to iterate over all elements in a numpy array you can use np.nditer()

To get every element of an array you can use a numpy fucntion called np.nditer()

In [56]:
#Creata 2D Numpy Arrays
nparraytwo = np.array([Weight_np,Height_np])
print(nparraytwo)
print(type(nparraytwo))

[[ 50.    60.    65.    70.    75.    80.    85.    90.    95.   100.  ]
 [  1.45   1.73   1.65   1.35   1.78   1.43   1.38   1.87   1.91   1.65]]
<class 'numpy.ndarray'>


In [65]:
#Code a for loop
for val in np.nditer(nparraytwo):
    print(val)

50.0
60.0
65.0
70.0
75.0
80.0
85.0
90.0
95.0
100.0
1.45
1.73
1.65
1.35
1.78
1.43
1.38
1.87
1.91
1.65
