### Numpy Package Python
NumPy is a Python library used for working with arrays, in which Numpy stands for (numerical python).

In Python we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy. Arrays are very frequently used in data science, where speed and resources are very important.

Why is Numpy faster ?
- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
- This behavior is called locality of reference in computer science.
- This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

Resource: W3schools

###### Import NumPy
Once NumPy is installed, import it in your applications by adding the import keyword:

In [5]:
#importing numpy library into python script
import numpy as np
#check numpy version
print("Numpy Version:", np.__version__)

Numpy Version: 1.18.5


###### Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [7]:
#Create a numpy array & save in variable
arr_1 = np.array([1,2,3,4,5,6,7,8,9,10])
#Type check data structure
print(type(arr_1))

<class 'numpy.ndarray'>


Furthermore create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray. Please see below and remember the syntax used to create tuples in Python

In [17]:
print("Tuple | ndarray")
print("")
#Create a tuple 
tuple_1 = (10,20,30)
print("Tuple", tuple_1)
print(type(tuple_1)) #print type of variable

#Create a NumPy array using tuple
arr_t = np.array((1, 2, 3, 4, 5))
print("ndarray created from tuple", arr_t)
print(type(arr_t))

#Pass a Tuple into the array() method used to create an ndarray object
tuple_new = (25,50,75,100)
ndarray_new = np.array(tuple_new)
print(tuple_new)
print(type(tuple_new))
print(ndarray_new)
print(type(ndarray_new))

Tuple | ndarray

Tuple (10, 20, 30)
<class 'tuple'>
ndarray created from tuple [1 2 3 4 5]
<class 'numpy.ndarray'>
(25, 50, 75, 100)
<class 'tuple'>
[ 25  50  75 100]
<class 'numpy.ndarray'>


In [18]:
print("List | ndarray")
print("")

#Create a List
List_1 = [2,5,7]
print("List", List_1)
print(type(List_1))

#Create a NumPy array using List
arr_l = np.array([1, 3, 4, 5])
print("ndarray created from List", arr_l)
print(type(arr_l))


List | ndarray

List [2, 5, 7]
<class 'list'>
ndarray created from List [1 3 4 5]
<class 'numpy.ndarray'>


###### Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).
nested array: are arrays that have arrays as their elements.

0-D Arrays
- 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [16]:
#0-D array with value
arr_a = np.array(42)
print(arr_a)
print(type(arr_a))

42
<class 'numpy.ndarray'>


1-D Arrays
- An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
- These are the most common and basic arrays.

In [20]:
#Create 1-D array containing values
arr_b = np.array([1, 2, 3, 4, 5])
print(arr_b)
print(type(arr_b))

[1 2 3 4 5]
<class 'numpy.ndarray'>


2-D Arrays
- An array that has 1-D arrays as its elements is called a 2-D array.
- These are often used to represent matrix or 2nd order tensor

In [23]:
#Create a 2-D array containing two arrays with values
arr_c = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_c)

[[1 2 3]
 [4 5 6]]


3-D arrays
- An array that has 2-D arrays (matrices) as its elements is called 3-D array.
- These are often used to represent a 3rd order tensor.

In [24]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with values
arr_d = np.array([[[1, 2, 3], [4, 5, 6]], [[11, 12, 13], [14, 15, 16]]])
print(arr_d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


###### Check Number of Dimensions in Ndarrays ?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [27]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print("ndarray dimensions")
print(a.ndim) #ndim attribute
print(b.ndim)
print(c.ndim)
print(d.ndim)

ndarray dimensions
0
1
2
3


###### Higher Dimensional Arrays
An array can have any number of dimensions. When the array is created, you can define the number of dimensions by using the ndmin argument.

In [29]:
arr_n = np.array([1, 2, 3, 4], ndmin=5) #ndmin argument
print(type(arr_n))
print(arr_n)
print('number of dimensions :', arr_n.ndim)

<class 'numpy.ndarray'>
[[[[[1 2 3 4]]]]]
number of dimensions : 5


### Conclusion
We have taken a look at some cool features of the data structure from the numpy package. This certainly seems like a cool place to hold data.